# Generated by Django 4.1.5 on 2023-08-04 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_canchas_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='H_in',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='H_out',
        ),
    ]
