# Generated by Django 4.1.5 on 2023-04-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('fe_in', models.DateField()),
                ('fe_sal', models.DateField()),
                ('nhuesped', models.CharField(max_length=10)),
                ('habtip', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
    ]
