# Generated by Django 4.1.5 on 2023-06-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('dias_trabajo', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=100)),
                ('horario_in', models.DateTimeField()),
                ('horario_out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='jornada',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo_marc', models.CharField(max_length=100)),
            ],
        ),
    ]
